#!/bin/bash

output_file=output.txt
dir=.
search='*'

if [ $1 ]; then 
	output_file=$1
fi

if [ $2 ]; then
	dir=$2
fi

if [ $3 ]; then
	search=$3
fi

for file in `find $dir -type f -name "*$search"`
do
	echo $file;
done > $output_file


